name: Detect secrets

permissions: {}

on:
  pull_request:
  merge_group:

jobs:
  detect-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@751276eafca55f10f252026015f43c488f2322ba
        with:
          python-version: "3.14"

      - name: Install Python dependencies
        run: "pip install --require-hashes --only-binary :all: -r .github/workflows/requirements.txt"

      - name: Detect secrets
        run: git ls-files -z | xargs -0 python -m detect_secrets.pre_commit_hook --verbose --baseline .secrets.baseline
