name: Upload Release Asset
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      
      - run: npm ci
      - run: npm run build-all

      - name: Zip dist
        run: |
          FILENAME="govuk-one-login-service-header-${{ github.event.release.tag_name || github.ref_name }}.zip"
          VERSION="${{ github.event.release.tag_name || github.ref_name }}"
          PROJECT_NAME="govuk-one-login-service-header"
          # theoretically this should zip dist without dist/govuk
          zip -r "$FILENAME" dist -x "dist/govuk/*"
          echo "ASSET_NAME=$FILENAME" >> $GITHUB_ENV

      - name: Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.ASSET_NAME }}
